apiVersion: v1
kind: Service
metadata:
  name: simple-service
  labels:
    run: simple-deploy
spec:
  ports:
    - name: http
      port: 9081
      protocol: TCP
      targetPort: 80
      nodePort: 32080
  type: NodePort
  selector:
    run: simple-deploy
